# Core dotfiles dependencies (run: brew bundle --file=~/dotfiles/Brewfile)

brew "bat"
brew "eza"
brew "fish"
brew "fzf"
brew "gh"
brew "ghq"
brew "lazygit"
brew "mise"
brew "ripgrep"
brew "starship"
brew "tmux"
brew "yabai"
brew "zoxide"
brew "zsh"

cask "karabiner-elements"
cask "font-jetbrains-mono-nerd-font"
cask "font-meslo-lg-nerd-font"
